# Generated by Django 3.2.2 on 2021-05-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210511_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_detail',
            new_name='Comments',
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date']},
        ),
    ]
